### ISSUE TITLE
cmake error, how to fix?

### ISSUE THREAD

**Issue by kemin711** [PacificBiosciences/pbbam#1]
cmake ../pbbam
-- The CXX compiler identification is GNU 4.8.4
-- The C compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:85 (find_package):
  Could not find a package configuration file provided by "htslib" with any
  of the following names:

    htslibConfig.cmake
    htslib-config.cmake

  Add the installation prefix of "htslib" to CMAKE_PREFIX_PATH or set
  "htslib_DIR" to a directory containing one of the above files.  If "htslib"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/kzhou/src/pacbio/buildbam/CMakeFiles/CMakeOutput.log".

**Comment by kemin711** [comment]
/usr/local$ find . -name 'htslib*'
./include/htslib
./lib/pkgconfig/htslib.pc
./lib/python2.7/dist-packages/pysam/htslib_util.h
./lib/python2.7/dist-packages/pysam/include/htslib
./lib/python2.7/dist-packages/pysam/include/htslib/htslib

htslib is install in /usr/local/  still got problems.

**Comment by nlhepler** [comment]
You'll need our copy of htslib, which has a couple fixes required for pbbam. It'll be built internally and linked statically.

**Comment by kemin711** [comment]
You mean, you need manual fix to the htslib and copy that source under the pbbam source directory?

 78 set(HTSLIB_INCLUDE_DIRS  "/usr/local/include/htslib")
 79 if(NOT HTSLIB_INCLUDE_DIRS OR
 80    NOT HTSLIB_LIBRARIES)
 81     if(HTSLIB_ROOTDIR)
 82         find_package(htslib
 83                      PATHS ${HTSLIB_ROOTDIR}/
 84                      REQUIRED)
 85     else()
 86         find_package(htslib
 87                      PATHS ${PacBioBAM_SOURCE_DIR}/../htslib/
 88                      REQUIRED)
 89     endif()
 90 endif()

I have added line 78, and it did not fix the problem.

**Comment by kemin711** [comment]
Now I have added proper directory for hitslib:

 86         find_package(htslib
 87                      PATHS ${PacBioBAM_SOURCE_DIR}/../../samtools/htslib/
 88                      REQUIRED)
You will need to add CMakeLists.txt to the htslib directory?

**Comment by dalexander** [comment]
@kemin711, do your homework before filing an issue.  If you want to see how to compile all the pbccs dependencies, take a look here: https://github.com/PacificBiosciences/pbccs/blob/master/circle.yml
