### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by 0xaf1f** [PacificBiosciences/pbbam#10]
It would help me to keep the Debian package up-to-date if you would tag releases (like the versions labeled in the changelog). We have a tool that can monitor the github tags/releases page and notify that the packaging needs to be updated. I'd really appreciate it--thanks for your consideration.

**Comment by EricDeveaud** [comment]
+1 for a tagged release

**Comment by pb-cdunn** [comment]
We maintain a large number of packages. Tagging each manually would be a lot of work, and the company is interested only in *sets* of packages.

We maintain the `master` and `develop` branches consistently across all our repos. If you want increasing numbers, you could use the date. But really, to us the "release" is the entire set of our software, not any specific package.

If you simply need a pre-built binary, and for some reason the whole "smrt" suite does not work for you, we unofficially release binaries of a useful subset of software (including **blasr**) which should work on a fair subset of recent Linux distros:
* https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries

We plan to cut a new binary release there today, actually.

**Comment by 0xaf1f** [comment]
> We maintain a large number of packages. Tagging each manually would be a lot of work, and the company is interested only in sets of packages.

I agree that it'd be too much work to go back and tag everything. But as things are going, it's not so much extra effort to throw in a `git tag ....` (especially when you already record a version within the program or changelog) and add `--tags` to your `git push` invocation, or alias it or whatever. Would that be feasible?
