### ISSUE TITLE
pacbio fork of htslib does not install cram/md5.h

### ISSUE THREAD

**Issue by rekado** [PacificBiosciences/pbbam#13]
pbbam source files expect to be able to include the header file "cram/md5.h", which is part of htslib, but the pacbio fork of htslib does not install this header file.

**Comment by armintoepfer** [comment]
Please report the executed commands and the error observed.

**Comment by rekado** [comment]
pbbam's `src/MD5.cpp` contains this line: `#include <cram/md5.h>`.  This assumes that this file is in one of the include paths.  When building pbbam with "-DHTSLIB_INCLUDE_DIRS=/path/to/pacbio-htslib/include" where `/path/to/pacbio-htslib` is the install prefix of the PacBio fork of htslib 1.1 then the build will fail.

In the Guix package for the PacBio fork of htslib 1.1 I fixed this by also installing all headers in the `cram` directory of htslib.

**Comment by armintoepfer** [comment]
Htslib is bundled within pbbam https://github.com/PacificBiosciences/pbbam/blob/master/third-party/htslib/htslib/cram/md5.h, I don't see the problem, plus you still haven't provided which tool has compilation issues

**Comment by rekado** [comment]
I know that htslib is bundled.  When providing packages for distributions, however, bundling is strongly discouraged, so I have separately packaged the PacBio fork of htslib and installed it.  The install target of the htslib fork does not install the cram headers.

pbbam offers a cmake flag to use htslib from a different location.  I'm pointing it to the *installed* htslib's "include" directory.

> plus you still haven't provided which tool has compilation issues

I don't understand the question.  I'm building pbbam from source with cmake.  I'm passing the following flags:

    -DHTSLIB_LIBRARIES=-lhts
    -DHTSLIB_INCLUDE_DIRS=/path/to/pacbio-htslib/include
    -DGTEST_SRC_DIR=/path/to/gtest-sources

Since you have already forked htslib it makes sense to alter its install target such that all required files are in fact installed.  Otherwise it won't be possible to build pbbam without using the bundled htslib sources (and that means that distributors will have to patch the sources or give up on packaging pbbam).

**Comment by adeslatt** [comment]
I just had the same problem -- did this resolve?  I am using straight out of the box pitchfork no separate build occuring

**Comment by armintoepfer** [comment]
pbbam doesn't bundle htslib anymore, but uses your system-wide installation.

**Comment by adeslatt** [comment]
so -- I guess the pacbio pitchfork build needs to be updated to handle this -- what is your advice -- where do I find the system-wide installation --

**Comment by armintoepfer** [comment]
This is a pitchfork issue, so best I can do is ping @mhsieh :)

**Comment by adeslatt** [comment]
Thanks for that -- I'll see if I can work around it.

**Comment by adeslatt** [comment]
what I did was comment out the htslib in the settings.mk and removed the directory from pitchfork_workdir and restarted with `make isoseq-core` lets see if this works.

**Comment by adeslatt** [comment]
so how do I get the version of pbbam that doesn't bundle htslib?

**Comment by SoapZA** [comment]
pbbam does not require the forked htslib anymore, any htslib 1.4 version and above should work.

Anyhow, please use the provided binaries from the SMRT link tarball or alternatively contact Tech Support for further assistance. Building our complete stack from source is daunting and requires advanced knowledge of buildsystems.
