### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by TakashiKoyama** [PacificBiosciences/pbbam#15]
Hi, I tried to install pbbam using pitchfork but got error as follows.
```
make[4]: Entering directory `/home/samba/Suijitsu_Public/software/pitchfork/workspace/pbbam/build'
[  1%] Building CXX object src/CMakeFiles/pbbam.dir/MD5.cpp.o
../../src/MD5.cpp:79:5: error: 'hts_md5_context' does not name a type
     hts_md5_context* data_;
     ^
../../src/MD5.cpp: In constructor 'PacBio::BAM::Md5ContextHelper::Md5ContextHelper()':
../../src/MD5.cpp:53:11: error: class 'PacBio::BAM::Md5ContextHelper' does not have any field named 'data_'
         : data_(hts_md5_init())
           ^
../../src/MD5.cpp:53:30: error: 'hts_md5_init' was not declared in this scope
         : data_(hts_md5_init())
                              ^
../../src/MD5.cpp:55:13: error: 'data_' was not declared in this scope
         if (data_ == nullptr)
             ^
../../src/MD5.cpp: In destructor 'PacBio::BAM::Md5ContextHelper::~Md5ContextHelper()':
../../src/MD5.cpp:61:25: error: 'data_' was not declared in this scope
         hts_md5_destroy(data_);
                         ^
../../src/MD5.cpp:61:30: error: 'hts_md5_destroy' was not declared in this scope
         hts_md5_destroy(data_);
                              ^
../../src/MD5.cpp: In member function 'std::string PacBio::BAM::Md5ContextHelper::Encoded(const string&)':
../../src/MD5.cpp:67:24: error: 'data_' was not declared in this scope
         hts_md5_update(data_, reinterpret_cast<void*>(const_cast<char*>(str.c_str())), str.size());
                        ^
../../src/MD5.cpp:67:98: error: 'hts_md5_update' was not declared in this scope
         hts_md5_update(data_, reinterpret_cast<void*>(const_cast<char*>(str.c_str())), str.size());
                                                                                                  ^
../../src/MD5.cpp:70:36: error: 'hts_md5_final' was not declared in this scope
         hts_md5_final(digest, data_);
                                    ^
../../src/MD5.cpp:73:38: error: 'hts_md5_hex' was not declared in this scope
         hts_md5_hex(hexdigest, digest);
                                      ^
make[4]: *** [src/CMakeFiles/pbbam.dir/MD5.cpp.o] Error 1
make[4]: Leaving directory `/home/samba/Suijitsu_Public/software/pitchfork/workspace/pbbam/build'
make[3]: *** [src/CMakeFiles/pbbam.dir/all] Error 2
make[3]: Leaving directory `/home/samba/Suijitsu_Public/software/pitchfork/workspace/pbbam/build'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/samba/Suijitsu_Public/software/pitchfork/workspace/pbbam/build'
make[1]: *** [/home/samba/Suijitsu_Public/software/pitchfork/workspace/pbbam/build/lib/libpbbam.so] Error 2
make[1]: Leaving directory `/home/samba/Suijitsu_Public/software/pitchfork/ports/pacbio/pbbam'
make: *** [pbbam] Error 2
```
Could you tell me how I can resolve this? Thank you for your kind helps!

**Comment by gzhang1986** [comment]
Hi, I am having the same problem, did you find a fix? I am installing isoseq using pitchfork, GCC 6.2.0
Thanks.
@TakashiKoyama

`[ 40%] Building CXX object src/CMakeFiles/pbbam.dir/MD5.cpp.o
cd /home/XXX/pkgs/pitchfork/workspace/pbbam/build/src && /usr/prog/GCC/6.2.0/bin/g++   -DPBBAM_LIBRARY -Dpbbam_EXPORTS -I/home/XXX/pkgs/pitchfork/workspace/pbbam/include -I/home/XXX/pkgs/pacbio/pitchfork_ToFU2_dev/src/htslib/include -I/home/XXX/pkgs/pacbio/pitchfork_ToFU2_dev/include  -fPIC -I/home/XXX/pkgs/pacbio/pitchfork_ToFU2_dev/include -D_GNU_SOURCE  -fPIC -I/home/XXX/pkgs/pacbio/pitchfork_ToFU2_dev/include -D_GNU_SOURCE  -fPIC -I/home/XXX/pkgs/pacbio/pitchfork_ToFU2_dev/include -D_GNU_SOURCE  -Wall -Wno-unused-local-typedefs -Wno-sign-compare -O2 -g -DNDEBUG -fPIC   -std=gnu++11 -o CMakeFiles/pbbam.dir/MD5.cpp.o -c /home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:79:5: error: ‘hts_md5_context’ does not name a type
     hts_md5_context* data_;
     ^~~~~~~~~~~~~~~
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp: In constructor ‘PacBio::BAM::Md5ContextHelper::Md5ContextHelper()’:
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:53:11: error: class ‘PacBio::BAM::Md5ContextHelper’ does not have any field named ‘data_’
         : data_(hts_md5_init())
           ^~~~~
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:53:30: error: ‘hts_md5_init’ was not declared in this scope
         : data_(hts_md5_init())
                              ^
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:55:13: error: ‘data_’ was not declared in this scope
         if (data_ == nullptr)
             ^~~~~
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp: In destructor ‘PacBio::BAM::Md5ContextHelper::~Md5ContextHelper()’:
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:61:25: error: ‘data_’ was not declared in this scope
         hts_md5_destroy(data_);
                         ^~~~~
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:61:30: error: ‘hts_md5_destroy’ was not declared in this scope
         hts_md5_destroy(data_);
                              ^
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp: In member function ‘std::__cxx11::string PacBio::BAM::Md5ContextHelper::Encoded(const string&)’:
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:67:24: error: ‘data_’ was not declared in this scope
         hts_md5_update(data_, reinterpret_cast<void*>(const_cast<char*>(str.c_str())), str.size());
                        ^~~~~
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:67:98: error: ‘hts_md5_update’ was not declared in this scope
         hts_md5_update(data_, reinterpret_cast<void*>(const_cast<char*>(str.c_str())), str.size());
                                                                                                  ^
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:70:36: error: ‘hts_md5_final’ was not declared in this scope
         hts_md5_final(digest, data_);
                                    ^
/home/XXX/pkgs/pitchfork/workspace/pbbam/src/MD5.cpp:73:38: error: ‘hts_md5_hex’ was not declared in this scope
         hts_md5_hex(hexdigest, digest);
                                      ^
make[4]: *** [src/CMakeFiles/pbbam.dir/MD5.cpp.o] Error 1
`

**Comment by TakashiKoyama** [comment]
Hi,

The htslib/hts.h in the pitchfork package seems not include hts_md5_context. I could avoid this error by replacing hts.h to another hts.h included in the samtools 1.3.1. However I got another error.

I gave up resolving this issue because the pitchfork package seems not to be maintained after releasing SMRTLink package. I recently try installing SMRTLink package. It's quite easy.

**Comment by gzhang1986** [comment]
@TakashiKoyama 
Thanks.
I tried another branch of pbbam it worked.
```
git clone https://github.com/PacificBiosciences/pbbam -b smrtlink-5.0.0 /home/XXX/pkgs/pitchfork/workspace/pbbam
```

**Comment by TakashiKoyama** [comment]
Great! Good luck!
