### ISSUE TITLE
Building with make fails on missing lzma dependency

### ISSUE THREAD

**Issue by seru71** [PacificBiosciences/pbbam#16]
Hi,

While trying to build the code on Ubuntu 16.04 I stumbled across problems with lzma lib.

[ 48%] Building CXX object tools/bam2sam/CMakeFiles/bam2sam.dir/__/common/OptionParser.cpp.o
[ 49%] Building CXX object tools/bam2sam/CMakeFiles/bam2sam.dir/src/main.cpp.o
[ 49%] Building CXX object tools/bam2sam/CMakeFiles/bam2sam.dir/src/Bam2Sam.cpp.o
[ 50%] Linking CXX executable ../../bin/bam2sam
/usr/local/lib/libhts.a(cram_io.o): In function `lzma_mem_deflate':
/ngs/software/src/htslib-1.6/cram/cram_io.c:669: undefined reference to `lzma_stream_buffer_bound'
/ngs/software/src/htslib-1.6/cram/cram_io.c:675: undefined reference to `lzma_easy_buffer_encode'
/usr/local/lib/libhts.a(cram_io.o): In function `cram_compress_by_method':
/ngs/software/src/htslib-1.6/cram/cram_io.c:1031: undefined reference to `BZ2_bzBuffToBuffCompress'
/usr/local/lib/libhts.a(cram_io.o): In function `cram_uncompress_block':
/ngs/software/src/htslib-1.6/cram/cram_io.c:957: undefined reference to `BZ2_bzBuffToBuffDecompress'
/usr/local/lib/libhts.a(cram_io.o): In function `lzma_mem_inflate':
/ngs/software/src/htslib-1.6/cram/cram_io.c:691: undefined reference to `lzma_easy_decoder_memusage'
/ngs/software/src/htslib-1.6/cram/cram_io.c:691: undefined reference to `lzma_stream_decoder'
/ngs/software/src/htslib-1.6/cram/cram_io.c:706: undefined reference to `lzma_code'
/ngs/software/src/htslib-1.6/cram/cram_io.c:719: undefined reference to `lzma_code'
/ngs/software/src/htslib-1.6/cram/cram_io.c:728: undefined reference to `lzma_end'
collect2: error: ld returned 1 exit status
tools/bam2sam/CMakeFiles/bam2sam.dir/build.make:148: recipe for target 'bin/bam2sam' failed
make[2]: *** [bin/bam2sam] Error 1
CMakeFiles/Makefile2:170: recipe for target 'tools/bam2sam/CMakeFiles/bam2sam.dir/all' failed
make[1]: *** [tools/bam2sam/CMakeFiles/bam2sam.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by seru71** [comment]
Found a solution by @kblin to a similar bug in blasr:
https://github.com/PacificBiosciences/blasr/issues/383

Here is a solution that worked for me:

```diff --git a/cmake/pbbam-dependencies.cmake b/cmake/pbbam-dependencies.cmake
index 8da899d..1b4023b 100644
--- a/cmake/pbbam-dependencies.cmake
+++ b/cmake/pbbam-dependencies.cmake
@@ -21,6 +21,20 @@ else()
     set(ZLIB_LDFLAGS ${ZLIB_LIBRARIES})
 endif()
 
+# LZMA
+if (NOT LIBLZMA_LIBRARIES)
+    find_package(LibLZMA REQUIRED)
+else()
+    set(LIBLZMA_LDFLAGS ${LIBLZMA_LIBRARIES})
+endif()
+
+# BZIP2
+if (NOT BZIP2_LIBRARIES)
+    find_package(BZip2 REQUIRED)
+else()
+    set(BZIP2_LDFLAGS ${BZIP2_LIBRARIES})
+endif()
+
 # htslib
 if(NOT HTSLIB_INCLUDE_DIRS OR NOT HTSLIB_LIBRARIES)
     find_package(HTSlib)
```

**Comment by pb-cdunn** [comment]
I like that idea. Alternatively, re-build **htslib** *without* **lzma** and **bzip2** support.
```
./configure --disable-bz2 --disable-lzma --enable-libcurl=no
```
