### ISSUE TITLE
trying to convert minimap2 mappings SAM

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/pbbam#19]
HI
I failed with this command: (ERROR: expected BAM, unknown format)

```
cat minimapped.sam | pbbamify reference.fasta subreads.bam > pb_minimap2.bam

# while the help says it should work right?
    --input=STR         The aligned non-PacBio BAM file. If not provided, stdin
                        will be used as input.
```

Any idea what should be tuned to take SAM as input for the mappings?

NB: it runs if I first convert SAM to BAM but this is overhead. I realise I could pipe minimap2 to samtools to output bam in the first place, this is my planB. :-)

THX

**Comment by isovic** [comment]
Hi Stephane,
`pbbamify` currently only accepts BAM as input, but your question is quite reasonable and we'll consider adding support for SAM in the future. For now, piping through `samtools` is the correct way to go (although not optimal in speed).
Best regards,
Ivan.

**Comment by splaisan** [comment]
Thanks Ivan
worked out nicely
S
