### ISSUE TITLE
pb.bam.tmp file very large

### ISSUE THREAD

**Issue by peritob** [PacificBiosciences/pbbam#23]
Hello PacBio team, 

I have a 36G aligned.bam from mapping raw fastq to denovo genome using minimap2 followed by samtools conversion. I am using pbbamify (with mydata.xml) to convert to pacbio suitable file for input to genomicconsensus/arrow. Pbbamify has been running for 36 hours and the tmp file is at 91G so far. Is this expected? I am a little concerned that starting with fastq (required by minimap2) and then using .xml from subreads.bam has corrupted the process. Can you please advise on the best steps?

Also, I should add that the subreads.bam were from both RSII (converted) and Sequel original reads
scripts:

dataset create mydata.xml *subreads.bam
pbbamify --input=aligned.bam --output=aligned.pb.bam my.fasta mydata.xml

many thanks,
Peri

**Comment by armintoepfer** [comment]
Yep. Large input leads to large output. You can also use `pbmm2` to map your subreads to the genome of interest and get output that can be polished.

**Comment by peritob** [comment]
For the benefit of others. The aligned.pb.bam otuput file was 350 GB - therefore 10 X the original aligned bam and took over 103 hours of walltime,  60 GB RAM but only one cpu. Perhaps there is a flag for threads but it is not in documentation.
