### ISSUE TITLE
add pbbamify to pbmm2

### ISSUE THREAD

**Issue by Arkarachai** [PacificBiosciences/pbbam#26]
I want to open this ticket in pbmm2, but there is no issue tab for me to use.
The quay.io/biocontainers/pbmm2:0.12.0--ha87ae23_0 pbmm2 don't have md5 for contig, so I have to use pbbamify to add it and sort BAM as well. I think it would be good if you bake-in pbbamify inside pbmm2 using and exposing an option to use it, so we don't have to do bamify and sort later.

**Comment by armintoepfer** [comment]
Please read and follow the documentation:
https://github.com/PacificBiosciences/pbmm2#availability
> Please refer to our official pbbioconda page for information on Installation, Support, License, Copyright, and Disclaimer.
This links to https://github.com/PacificBiosciences/pbbioconda.

We can discuss there.
