### ISSUE TITLE
Issues with arrow and pbbamify

### ISSUE THREAD

**Issue by sum732** [PacificBiosciences/pbbam#27]
Hi Team,
I am trying to perform some variant analysis.  I tried to use "arrow" for variant calling and was given a warning message the program quit. 
```
PacBio arrow -j5 ../alignment/lbc_0009_OGI655_1331.out.aligned.bam -r /data/genomes/RNASeq/Human/GRCh37/PacBio/reference/ucsc.hg19.rCRS.fasta -o lbc_0009_OGI655_1331.vcf                                                                                                                                                                                       
[WARNING] pbi file missing for /gpfs/fs1/data/RNA_Collaboration/PacBio/GEDi_Hilary/data/FromFastq/deMux/fastq/alignment/lbc_0009_OGI655_1331.out.aligned.bam, operating with reduced speed and functionality
```

So I tried to make the index
```
echo "PacBio pbbamify /data/PacBio/reference/ucsc.hg19.rCRS.fasta lbc_0009_OGI655_1331.out.aligned.bam lbc_0009_OGI655_1331.pb.bam" | qsub  -V -cwd -pe multi-thread 2 -e qsubPacBiopbbamify.err -o qsubPacBiopbbamify.out -N "pbbamify"
```
and I am seeing following error message
```
ERROR: BamFile: expected BAM, encountered un supported format: -
```
The reads were aligned using PacBio  "pbmm2 align".
There is no issues with running samtools flagstats and other tools for downstream analysis. I am not sure how to go about this issue. I want to make variant calls using "arrow"

**Comment by armintoepfer** [comment]
You can create the pbi with `pbindex` that is part of `conda install pbbam`

**Comment by armintoepfer** [comment]
Usually, pbmm2 generates the pbi if you used `--sort`. Please try that pbmm2 call again with sorting and let us know. And name sure you have the latest pbmm2 version `conda update --all`

**Comment by armintoepfer** [comment]
Sounds like the execution didn't finish. Can you give a new try?

What does `pbmm2 --version` tell you?

**Comment by armintoepfer** [comment]
GenomicConsensus is a synonym for arrow. 

You can't polish if you use `.fastq` as input. You must use `.subreads.bam` as `pbmm2 align` input. Here is a trick: Run `pbmm2 align` with the `.subreads.bam` as input, omit `--rg` as that's already present in the input BAM file and use `out.alignmentset.xml` as output type.

We'll push out a new `gcpp` version, the new implementation of `arrow`, soon. It will support `.bai` and won't depend on `.pbi`

**Comment by armintoepfer** [comment]
This is beyond app support we can offer on GitHub. Please refer to PacBio's techsupport for those individual problems.

**Comment by armintoepfer** [comment]
There is little to no difference in running lima on subreads or ccs. Lima tolerates sequencing errors by design. For further help please refer to https://www.pacb.com/support/technical-support/
