### ISSUE TITLE
Where to find libpbbam.dylib?

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/pbbam#4]
Hi,

I have complied pbbam as described in "Getting Started" (http://pbbam.readthedocs.io/en/latest/getting_started.html), with only a modification in the cmake command:

cmake .. -DHTSLIB_ROOTDIR="/opt/htslib" -DGTEST_SRC_DIR="/opt/googletest"

I can run all the commands successfully without errors (including 'make test'), but I can't find libpbbam.dylib in the 'build folder.

I would have expected to see it in the 'lib' folder, but I can only see the source file 'libpbbam.a'.  I know that libpbbam.dylib is required for blasr (and possibly others), so I am wondering if there is something I should do differently when compiling pbbam.

Thanks,
Charles

**Comment by pezmaster31** [comment]
pbbam only builds a static version of the library by default. You should be able to turn shared-lib compilation on by adding:

    -DPacBioBAM_build_shared=ON

to your CMake command.

**Comment by cwarden45** [comment]
Ok - great.  I can now see libpbbam.dylib in the 'lib' subfolder.

However, I noticed that 'make test' now fails:

```
Running tests...
Test project /opt/pbbam/build
    Start 1: bam2sam_CramTests
1/4 Test #1: bam2sam_CramTests ................***Failed    0.69 sec
    Start 2: pbindexdump_CramTests
2/4 Test #2: pbindexdump_CramTests ............***Failed    0.08 sec
    Start 3: pbmerge_CramTests
3/4 Test #3: pbmerge_CramTests ................***Failed    0.74 sec
    Start 4: UnitTests
4/4 Test #4: UnitTests ........................***Exception: Other  0.01 sec

0% tests passed, 4 tests failed out of 4

Total Test time (real) =   1.53 sec

The following tests FAILED:
	  1 - bam2sam_CramTests (Failed)
	  2 - pbindexdump_CramTests (Failed)
	  3 - pbmerge_CramTests (Failed)
	  4 - UnitTests (OTHER_FAULT)
Errors while running CTest
make: *** [test] Error 8

```
Is there a way to correct his problem?

**Comment by cwarden45** [comment]
Also, I noticed that the libpbbam.a is now deleted (so, if I recompile, I'm guessing that I need to re-download the code)

**Comment by cwarden45** [comment]
For my purposes, it looks like I have fixed my issue with .bam file input for blasr (https://github.com/PacificBiosciences/blasr/issues/232), so I will close this issue
